// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gpblyguzogolyhbwbxtc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdwYmx5Z3V6b2dvbHloYndieHRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MDg5ODIsImV4cCI6MjA3MzE4NDk4Mn0.8DF6grr-YmTd9dsrDkCbaY2l9MalLwSNV10YE_z0xuU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});